name: mandar_trip
version: 1.0.0+1
publish_to: none
description: IMPLEMENTASI FRAMEWORK FLUTTER SISTEM INFORMASI PARIWISATA DI KABUPATEN POLEWALI MANDAR DENGAN METODE LOCATION BASED SERVICE (LBS).
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.17.1
  get_storage: 2.0.3
  flutter_svg: 1.0.3
  firebase_auth: 3.3.19
  cloud_firestore: 3.1.17
  salomon_bottom_bar: ^3.3.1
  custom_info_window: ^1.0.1
  sliding_up_panel: ^2.0.0+1
  flutter_slidable: ^1.3.0
  google_maps_flutter: 2.1.5
  geolocator: ^8.2.1
  flutter_native_splash: ^2.1.6
  flutter_polyline_points: ^1.0.0
  image_picker: 0.8.5+3
  firebase_storage: 10.2.18
  location: ^4.4.0
  intl: 0.17.0
  cached_network_image: 3.2.0
  avatar_glow: 2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/logo/logo_dark.png
  color: "#FFFFFF"
  image_dark: assets/logo/logo_light.png
  color_dark: "#000000"

flutter:
  assets:
    - assets/svg/
    - assets/icons/
    - assets/logo/
    - assets/map/
  uses-material-design: true
